name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: docker.io
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          # Get the release version from docker-bake.hcl
          RELEASE=$(grep 'default = "v' docker-bake.hcl | head -1 | sed 's/.*"\(v[^"]*\)".*/\1/')
          echo "release=$RELEASE" >> $GITHUB_OUTPUT
          
          # Determine if this is a tag push
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        run: |
          docker buildx bake -f docker-bake.hcl cu124-py312 --push
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REGISTRY_USER: ${{ env.REGISTRY_USER }}
          RELEASE: ${{ steps.meta.outputs.release }}

      - name: Image digest
        run: echo "Image pushed successfully for cu124-py312"
